version: '3.8'

services:
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=db
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    depends_on:
      - mysql
    image: arijhakouna/tpfoyer:${DOCKER_TAG:-latest}
    restart: always 
    ports:
      - 8089:8089
    environment:
      SPRING_PROFILES_ACTIVE: docker
    stdin_open: true
    tty: true

volumes:
  mysql_data: 
