version: '3.8'

services:
  # Base de données MySQL
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - tpfoyer_network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'
      placement:
        constraints:
          - node.role == manager

  # Application Spring Boot
  app:
    image: arijhakouna/tpfoyer:${DOCKER_TAG:-latest}
    ports:
      - "8089:8089"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - tpfoyer_network
    depends_on:
      - mysql
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5
      resources:
        limits:
          memory: 1G
          cpus: '1.0'
        reservations:
          memory: 512M
          cpus: '0.5'
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
      rollback_config:
        parallelism: 1
        delay: 5s
        order: stop-first

volumes:
  mysql_data:
    driver: local

networks:
  tpfoyer_network:
    driver: overlay
    attachable: true 